<?php
$myaddons = array();
$maNum = 0;
$myaddons[$maNum] = array('2046', '/uploads/allimg/171123/1-1G1231K529415.png');
$maNum = 1;
$myaddons[$maNum] = array('2047', '/uploads/allimg/171123/1-1G1231K554429.png');
$maNum = 2;
$myaddons[$maNum] = array('2048', '/uploads/allimg/171123/1-1G1231K610345.png');
$maNum = 3;
$myaddons[$maNum] = array('2049', '/uploads/allimg/171123/1-1G1231K625213.png');
$maNum = 4;
