<?php
$typeArr[21] = '婴童床品';
$typeArr[2] = '品牌故事';
$typeArr[3] = '产品中心';
$typeArr[4] = '婴儿推车';
$typeArr[5] = '婴儿床';
$typeArr[6] = '安全座椅';
$typeArr[8] = '童装服装';
$typeArr[9] = '周边产品';
$typeArr[10] = '新闻资讯';
$typeArr[11] = '媒体报道';
$typeArr[12] = '行业资讯';
$typeArr[13] = '选购技巧';
$typeArr[14] = '联系我们';
$typeArr[15] = '幻灯';
$typeArr[16] = '产品热区';
$typeArr[17] = '类别';
$typeArr[18] = '新闻-产品管理';
$typeArr[19] = '首页管理';
?>