<img class="img-responsive center-block" src="[field:tp1/]" alt="">
                    <img style="display:none;" class="img-responsive center-block" src="[field:tp2/]" alt="">
                    <div class="text-center img-text">
                   <a href="/products/tzfs/">   <p class="en">[field:yw/]</p>
                        <div class="dark">
                            <p class="zh">[field:dymc/]</p>
                        </div>
                        <div class=" light" style="">
                            <p class="light-t">[field:demc/]</p>
                            <div class="light-in hidden-xs hidden-sm">
                               [field:js/]
                               </a>
                            </div>