<?php
$z[0]=Array("pubdate","",259,305);
$z[0][4]=array();
$z[0][4]['function']="strftime(\"%Y\",@me)";
$z[1]=Array("pubdate","",311,357);
$z[1][4]=array();
$z[1][4]['function']="strftime(\"%b\",@me)";
$z[2]=Array("title","",396,410);
$z[2][4]=array();
$z[3]=Array("description","",441,462);
$z[3][4]=array();
$z[4]=Array("litpic","",597,612);
$z[4][4]=array();
$z[5]=Array("title","",619,633);
$z[5][4]=array();

?>