<div class="row article-first">

                                    <div class="col-sm-6" style="position: relative;">

                                     <h3>[field:pubdate function='strftime("%b %d/ %Y",@me)'/]<div class="f-bt-collect"><a href="javascript:window.external.addfavorite('{dede:global.cfg_basehost/}{dede:field.id

runphp='yes'}$id=@me;@me='';$url=GetOneArchive($id);@me=$url['arcurl'];{/dede:field.id}','{dede:field.title/}')">收藏</a></div></h3>

                                        <p class="article-tit"><a href="[field:arcurl/]" target="_blank">[field:title/]</a></p>

                                        <p class="article-con">[field:description/]</p>

                                       <a href="[field:arcurl/]" style="position: absolute; left: 44%; top: 132%;"><img src="/templets/default/image/eyes.png" style="position: absolute;display:none;left: 40%;top: 232%;" class="eyes-img" alt=""></a>

                                    </div>    

                                    <div class="col-sm-6 first-newspic hidden-xs hidden-sm">

                                    <a href="[field:arcurl/]" target="_blank"><img src='[field:litpic/]' style="width:100%;" alt="[field:title/]"></a> 

                                    </div>

                                    <div class="clearfix"></div>

                                    <div class="article-line"></div>

                                </div>