<?php
$z[0]=Array("mid","",257,303);
$z[0][4]=array();
$z[0][4]['function']="GetMemberInfo(@me,sex)";
$z[1]=Array("mid","",309,357);
$z[1][4]=array();
$z[1][4]['function']="GetMemberInfo(@me,uname)";
$z[2]=Array("title","",396,410);
$z[2][4]=array();
$z[3]=Array("body","",441,454);
$z[3][4]=array();
$z[4]=Array("litpic","",569,584);
$z[4][4]=array();
$z[5]=Array("title","",591,605);
$z[5][4]=array();

?>