<li>

				<a href="/products/tzfs/"><img src="[field:plmctp2/]" alt="[field:plmc1/]"></a>

				<p>[field:plmc1/]</p>

			</li>

			<li>

				<a href="/products/yetc/"><img src="[field:plmctp4/]" alt="[field:plmc2/]"></a>

				<p>[field:plmc2/]</p>

			</li>

			<li>

				<a href="/products/yec/"><img src="[field:plmctp6/]" alt="[field:plmc3/]"></a>

				<p>[field:plmc3/]</p>

			</li>

			<li>

				<a href="/products/aqzy/"><img src="[field:plmctp8/]" alt="[field:plmc4/]"></a>

				<p>[field:plmc4/]</p>

			</li>

			<li>

				<a href="/products/etcp/"><img src="[field:plmctp10/]" alt="[field:plmc5/]"></a>

				<p>[field:plmc5/]</p>

			</li>

			<li>
             	<a href="/products/zbcp"><img src="[field:plmctp12/]" alt="[field:plmc6/]"></a>

				<p>[field:plmc6/]</p>
				

			</li>