<div class="vertical-timeline-content">

                	<div class="vertical-position">

	                    <h2>[field:source/]<span>[field:writer/]</span></h2>

	                      <h3>[field:title/]</h3>

	                    <p>[field:body/]</p>

                		

                	</div>

                    <span class="vertical-date">

                    	 <img src="[field:litpic/]" alt="[field:title/]">

					</span>

                </div>