<div class="vertical-timeline-block">

                <div class="vertical-timeline-icon blue-bg">     

                </div>

                <div class="vertical-timeline-content">

                	<div class="vertical-position">

	                     <h2>[field:source/]<span>[field:writer/]</span></h2>

	                    <h3>[field:title/]</h3>

	                    <p>[field:body function='cn_substr(html2text(@me),600)'/]</p>

                	</div>

                    <span class="vertical-date">

                    	<img src="[field:litpic/]" alt="[field:title/]">

                    </span>

                </div>

            </div>