<div class="item active">
		      <img src="[field:hdtp/]" style="width:100%" alt="">
		      <div class="carousel-caption animated bounceInDown">
		        <h2>[field:hd1/]</h2>
		        <h5 class="hidden-xs">[field:hd2/]</h5>
		      </div>
		    </div>

		    <div class="item">
		    <img src="[field:hdtp2/]" style="width:100%" alt="">
		      <div class="carousel-caption animated bounceInDown">
		        <h2>[field:hd3/]</h2>
		        <h5 class="hidden-xs">[field:hd4/]</h5>
		      </div>
		    </div>
		    <div class="item">
		     <img src="[field:hdtp3/]" style="width:100%" alt="">
		      <div class="carousel-caption animated bounceInDown" id="delay">
		         <h2>[field:hd5/]</h2>
		        <h5 class="hidden-xs">[field:hd6/]</h5>
		      </div>
		    </div>