<div class="col-sm-6">
                <img class="left-img img-responsive center-block" src="[field:lbt /]" alt="">
            </div>
            <div class="col-sm-6">
                <div class="productc-top-right">

                    <div class="t">
                        <div class="c-logo">
                          <h3> [field:fulltitle/]</h3>                          
                        </div>
                        <span class="pull-right">新品推荐 New Arrival</span>
                    </div>
                    <div class="c-con">
                        <h3>[field:fulltitle/]</h3>
                      [field:body/]

                       <a href="[field:arcurl/]" title="[field:fulltitle /]" target="_blank"><< 查看详情</a>
                    </div>
                </div>