
<field:yw1 itemname="第一英文标题" autofield="1" notsend="0" type="multitext" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:yw1>

<field:zw1 itemname="第一中文标题" autofield="1" notsend="0" type="multitext" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:zw1>

<field:yw2 itemname="第二英文标题" autofield="1" notsend="0" type="multitext" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:yw2>
