<field:banner itemname="内容banner(不能大于500K)" autofield="1" notsend="0" type="imgfile" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:banner>
<field:lb itemname="产品类别" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:lb>
<field:rq itemname="适用人群" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:rq>
<field:logo itemname="LOGO型号图标" autofield="1" notsend="0" type="imgfile" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:logo>
<field:lbt itemname="轮播图-1" autofield="1" notsend="0" type="imgfile" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:lbt>
<field:lbt2 itemname="轮播图-2" autofield="1" notsend="0" type="imgfile" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:lbt2>
<field:lbt3 itemname="轮播图-3" autofield="1" notsend="0" type="imgfile" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:lbt3>
<field:lbt4 itemname="轮播图-4" autofield="1" notsend="0" type="imgfile" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:lbt4>
<field:lb5 itemname="轮播图-5" autofield="1" notsend="0" type="imgfile" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:lb5>
<field:cz itemname="内容左侧图片" autofield="1" notsend="0" type="imgfile" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:cz>
<field:nr itemname="内容底部图片" autofield="1" notsend="0" type="imgfile" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:nr>
<field:czgy itemname="材质工艺" autofield="1" notsend="0" type="htmltext" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:czgy>
<field:cczl itemname="尺寸重量" autofield="1" notsend="0" type="htmltext" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:cczl>
<field:ysys itemname="颜色样式" autofield="1" notsend="0" type="htmltext" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:ysys>
<field:bjzc itemname="部件组成" autofield="1" notsend="0" type="htmltext" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:bjzc>
<field:yssp itemname="演示视频" autofield="1" notsend="0" type="media" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:yssp>
<field:English itemname="英文" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:English>
<field:body itemname="详细介绍" autofield="1" notsend="0" type="htmltext" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:body>
