<field:yw itemname="英文体" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:yw>
<field:zw itemname="中文体" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:zw>
<field:pp itemname="品牌地图图片" autofield="1" notsend="0" type="imgfile" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:pp>
<field:gq1 itemname="国旗1" autofield="1" notsend="0" type="imgfile" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:gq1>
<field:gj1 itemname="国家名称1" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:gj1>
<field:gq2 itemname="国旗2" autofield="1" notsend="0" type="imgfile" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:gq2>
<field:gj2 itemname="国家名称2" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:gj2>
<field:gq3 itemname="国旗3" autofield="1" notsend="0" type="imgfile" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:gq3>
<field:gj3 itemname="国家名称3" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:gj3>
<field:gq4 itemname="国旗4" autofield="1" notsend="0" type="imgfile" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:gq4>
<field:gj4 itemname="国家名称4" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:gj4>
<field:gq5 itemname="国旗5" autofield="1" notsend="0" type="imgfile" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:gq5>
<field:gj5 itemname="国家名称5" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:gj5>
<field:gq6 itemname="国旗6" autofield="1" notsend="0" type="imgfile" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:gq6>
<field:gj6 itemname="国家名称6" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:gj6>
<field:gq7 itemname="国旗7" autofield="1" notsend="0" type="imgfile" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:gq7>
<field:gj7 itemname="国家名称7" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:gj7>
<field:gq8 itemname="国旗8" autofield="1" notsend="0" type="imgfile" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:gq8>
<field:gj8 itemname="国家名称8" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:gj8>
<field:gq9 itemname="国旗9" autofield="1" notsend="0" type="imgfile" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:gq9>
<field:gj9 itemname="国家名称9" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:gj9>

<field:gq10 itemname="国旗10" autofield="1" notsend="0" type="imgfile" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:gq10>

<field:gj10 itemname="国家名称10" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:gj10>

<field:plmc1 itemname="品类名称1" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:plmc1>

<field:plmctp1 itemname="品类名称图片-鼠标前-1" autofield="1" notsend="0" type="imgfile" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:plmctp1>






<field:plmctp2 itemname="品类名称图片-鼠标后-1 " autofield="1" notsend="0" type="imgfile" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:plmctp2>

<field:plmc2 itemname="品类名称2" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:plmc2>

<field:plmctp3 itemname="品类名称图片-鼠标前-2" autofield="1" notsend="0" type="imgfile" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:plmctp3>

<field:plmctp4 itemname="品类名称图片-鼠标后-2" autofield="1" notsend="0" type="imgfile" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:plmctp4>

<field:plmc3 itemname="品类名称3" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:plmc3>

<field:plmctp5 itemname="品类名称图片-鼠标前-3" autofield="1" notsend="0" type="imgfile" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:plmctp5>

<field:plmctp6 itemname="品类名称图片-鼠标后-3" autofield="1" notsend="0" type="imgfile" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:plmctp6>

<field:plmc4 itemname="品类名称4" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:plmc4>

<field:plmctp7 itemname="品类名称图片-鼠标前4" autofield="1" notsend="0" type="imgfile" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:plmctp7>

<field:plmctp8 itemname="品类名称图片-鼠标后4" autofield="1" notsend="0" type="imgfile" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:plmctp8>

<field:plmc5 itemname="品类名称5" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:plmc5>

<field:plmctp9 itemname="品类名称图片-鼠标前5" autofield="1" notsend="0" type="imgfile" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:plmctp9>

<field:plmctp10 itemname="品类名称图片-鼠标后5" autofield="1" notsend="0" type="imgfile" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:plmctp10>
