<div class="vertical-timeline-block">
                <div class="vertical-timeline-icon navy-bg">
                </div>
                <div class="vertical-timeline-content">
                	<div class="vertical-position">
	                 <h2>[field:pubdate function='strftime("%Y",@me)'/]<span>[field:pubdate function='strftime("%b",@me)'/]</span></h2>
	                    <h3>[field:title/]</h3>
	                    <p>[field:body/]</p>
                	</div>
                    <span class="vertical-date">
                        <img src="[field:litpic/]" alt="[field:title/]">
                    </span>
                </div>
            </div>