<?php
$z[0]=Array("pubdate","",254,300);
$z[0][4]=array();
$z[0][4]['function']="strftime(\"%Y\",@me)";
$z[1]=Array("pubdate","",306,352);
$z[1][4]=array();
$z[1][4]['function']="strftime(\"%b\",@me)";
$z[2]=Array("title","",391,405);
$z[2][4]=array();
$z[3]=Array("body","",436,449);
$z[3][4]=array();
$z[4]=Array("litpic","",564,579);
$z[4][4]=array();
$z[5]=Array("title","",586,600);
$z[5][4]=array();

?>