<?php
$z[0]=Array("pubdate","",299,345);
$z[0][4]=array();
$z[0][4]['function']="strftime(\"%Y\",@me)";
$z[1]=Array("pubdate","",351,397);
$z[1][4]=array();
$z[1][4]['function']="strftime(\"%b\",@me)";
$z[2]=Array("title","",436,450);
$z[2][4]=array();
$z[3]=Array("description","",481,502);
$z[3][4]=array();
$z[4]=Array("litpic","",614,629);
$z[4][4]=array();
$z[5]=Array("title","",636,650);
$z[5][4]=array();

?>