<field:hd1 itemname="幻灯1大标题" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:hd1>
<field:hd2 itemname="幻灯1小标题" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:hd2>
<field:hdtp itemname="幻灯1图片" autofield="1" notsend="0" type="imgfile" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:hdtp>



<field:hd3 itemname="幻灯2大标题" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:hd3>
<field:hd4 itemname="幻灯2小标题" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:hd4>
<field:hdtp2 itemname="幻灯2图片" autofield="1" notsend="0" type="imgfile" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:hdtp2>



<field:hd5 itemname="幻灯3大标题" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:hd5>
<field:hd6 itemname="幻灯3小标题" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:hd6>
<field:hdtp3 itemname="幻灯3图片" autofield="1" notsend="0" type="imgfile" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:hdtp3>




<field:hd10 itemname="幻灯4大标题" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:hd10>

<field:hd11 itemname="幻灯4小标题 " autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:hd11>
