<?php
$z[0]=Array("pubdate","",166,219);
$z[0][4]=array();
$z[0][4]['function']="strftime(\"%b %d/ %Y\",@me)";
$z[1]=Array("arcurl","",549,564);
$z[1][4]=array();
$z[2]=Array("title","",582,596);
$z[2][4]=array();
$z[3]=Array("description","",671,691);
$z[3][4]=array();
$z[4]=Array("arcurl","",747,762);
$z[4][4]=array();
$z[5]=Array("arcurl","",1142,1157);
$z[5][4]=array();
$z[6]=Array("litpic","",1185,1225);
$z[6][4]=array();
$z[6][4]['function']="firstimg('@me')";
$z[7]=Array("title","",1252,1266);
$z[7][4]=array();

?>