<li>
                                                <div class="post-widget-image">
                                                   <a href="[field:arcurl/]"  target="_blank">
                                                    <img width="50" height="50" src="[field:litpic/]" alt="[field:title/]" class="attachment-blog-widget size-blog-widget wp-post-image" sizes="(max-width: 50px) 100vw, 50px">
                                                    </a>
                                                </div>
                                                <div class="post-widget-text">
                                                   <a href="[field:arcurl/]"  target="_blank">[field:fulltitle/]</a>
                                                    <span>[field:pubdate function="GetDateMK(@me)"/]</span>
                                                </div>
                                                <div class="clear"></div>
                                            </li>