<?php
$z[0]=Array("pubdate","",277,323);
$z[0][4]=array();
$z[0][4]['function']="strftime(\"%Y\",@me)";
$z[1]=Array("pubdate","",329,375);
$z[1][4]=array();
$z[1][4]['function']="strftime(\"%b\",@me)";
$z[2]=Array("title","",414,428);
$z[2][4]=array();
$z[3]=Array("description","",459,480);
$z[3][4]=array();
$z[4]=Array("litpic","",592,607);
$z[4][4]=array();
$z[5]=Array("title","",614,628);
$z[5][4]=array();

?>