
<field:hd1 itemname="幻灯1大标题" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:hd1>

<field:hd2 itemname="幻灯1小标题" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:hd2>

<field:hdtp itemname="幻灯1图片" autofield="1" notsend="0" type="imgfile" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:hdtp>

<field:hd3 itemname="幻灯2大标题" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:hd3>
