<div class="t">
                        <div class="c-logo">
                            <img src=" [field:logo /]" alt=""> 
                            <span>(2017)</span>
                            
                        </div>
                        <span class="pull-right">新品推荐 News Arrivals</span>
                    </div>
                    <div class="c-con">
                        <h3>[field:fulltitle/]</h3>
                      [field:l.body/]

                        <a href=""><< 查看详情</a>
                    </div>
                </div>