<!-- <a href="[field:lb1lj/]"></a>--><a href="javascript:;">[field:lb1/]</a>
            <span style="color:white;font-size:18px">|</span>
           <!-- <a href="[field:lb2lj/]"></a>--><a href="javascript:;">[field:lb2/]</a>
            <span style="color:white;font-size:18px">|</span>
           <!-- <a href="[field:lb3lj/]"></a>--><a href="javascript:;">[field:lb3/]</a>
            <span style="color:white;font-size:18px">|</span>
            <!--<a href="[field:lb4lj/]"></a>--><a href="javascript:;">[field:lb4/]</a>