<?php
$z[0]=Array("pubdate","",276,322);
$z[0][4]=array();
$z[0][4]['function']="strftime(\"%Y\",@me)";
$z[1]=Array("pubdate","",328,374);
$z[1][4]=array();
$z[1][4]['function']="strftime(\"%b\",@me)";
$z[2]=Array("title","",413,427);
$z[2][4]=array();
$z[3]=Array("description","",458,479);
$z[3][4]=array();
$z[4]=Array("litpic","",611,626);
$z[4][4]=array();
$z[5]=Array("title","",633,647);
$z[5][4]=array();

?>