
<field:lb itemname="产品类别" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:lb>

<field:rq itemname="适用人群" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:rq>

<field:LOGO itemname="LOGO型号图标" autofield="1" notsend="0" type="img" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:LOGO>

<field:lbt itemname="轮播图-1" autofield="1" notsend="0" type="img" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:lbt>

<field:lbt2 itemname="轮播图-2" autofield="1" notsend="0" type="img" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:lbt2>

<field:lbt3 itemname="轮播图-3" autofield="1" notsend="0" type="img" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:lbt3>
