<field:lb itemname="产品类别" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:lb>
<field:rq itemname="适用人群" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:rq>
<field:LOGO itemname="LOGO" autofield="1" notsend="0" type="img" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:LOGO>
<field:1 itemname="第一张图" autofield="1" notsend="0" type="img" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:1>
<field:2 itemname="第二张图" autofield="1" notsend="0" type="img" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:2>
<field:4 itemname="第三张图" autofield="1" notsend="0" type="img" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:4>
<field:5 itemname="第四张图" autofield="1" notsend="0" type="img" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:5>
<field:sms itemname="材质工艺" autofield="1" notsend="0" type="htmltext" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:sms>
<field:cczl itemname="尺寸重量" autofield="1" notsend="0" type="htmltext" isnull="true" islist="0" default=""  maxlength="400" page="">
</field:cczl>
<field:ysys itemname="颜色样式" autofield="1" notsend="0" type="htmltext" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:ysys>
<field:zzbj itemname="部件组成" autofield="1" notsend="0" type="htmltext" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:zzbj>
<field:yssb itemname="演示视频" autofield="1" notsend="0" type="media" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:yssb>
<field:yy itemname="英文" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="600" page="">
</field:yy>
<field:body itemname="详细介绍" autofield="1" notsend="0" type="htmltext" isnull="true" islist="0" default=""  maxlength="" page="split">	
</field:body>	
