<div class="item active">
		      <img src="[field:hdtp/]" style="width:100%" alt="">
		      <div class="carousel-caption animated fadeInDown
">
		        <h2>[field:hd1/]</h2>
		        <h5>[field:hd2/]</h5>
		      </div>
		    </div>

		    <div class="item">
		    <img src="[field:hdtp2/]" style="width:100%" alt="">
		      <div class="carousel-caption animated fadeInDown">
		        <h2>[field:hd3/]</h2>
		        <h5>[field:hd4/]</h5>
		      </div>
		    </div>
		    <div class="item">
		     <img src="[field:hdtp3/]" style="width:100%" alt="">
		      <div class="carousel-caption animated fadeInDown">
		         <h2>[field:hd4/]</h2>
		        <h5>[field:hd5/]</h5>
		      </div>
		    </div>