<?php
$z[0]=Array("pubdate","",260,306);
$z[0][4]=array();
$z[0][4]['function']="strftime(\"%Y\",@me)";
$z[1]=Array("pubdate","",312,358);
$z[1][4]=array();
$z[1][4]['function']="strftime(\"%b\",@me)";
$z[2]=Array("title","",397,411);
$z[2][4]=array();
$z[3]=Array("description","",442,463);
$z[3][4]=array();
$z[4]=Array("litpic","",597,612);
$z[4][4]=array();
$z[5]=Array("title","",619,633);
$z[5][4]=array();

?>