<div class="t hidden-xs">
                        <div class="c-logo">
                            <img src="[field:logo /]" alt=""> 
          
                        </div>
                     <span class="pull-right">New Arrival</span>
                    </div>
                    <div class="c-con">
                        <h3>[field:fulltitle/]</h3>
                           [field:body/]

                       <a href="[field:arcurl/]" title="[field:fulltitle /]" target="_blank"><< Details</a>
                    </div>
                </div>