<img src="[field:litpic/]" alt="[field:title/]" style="height: auto; width:100%;bottom: -55px; top: -334px; left: 0px; opacity: 1; transform: matrix(1.005, 0, 0, 1.005, 0, 0);">
    <div class="col span_12 dark left">
        <div class="inner" style="top: 144.5px; opacity: 1;">
        <span><i>下一篇</i></span>
       <a href="[field:arcurl/]"  target="_blank"><h3>[field:fulltitle/]</h3></a> 
        </div>
    </div>
    <span class="full-link">
        <a href="[field:arcurl/]"  target="_blank">[field:fulltitle/]</a> 
    </span>
    <span class="bg-overlay"></span>