
    <m:item name='新闻资讯' ischannel='1' link='content_list.php?channelid=1' linkadd='article_add.php?channelid=1' channelid='1' rank='' target='main' />
  <m:item name='品牌故事大事件' ischannel='1' link='content_ppgs.php?channelid=18' linkadd='ppgs_add.php?channelid=18' channelid='18' rank='' target='main' />
  <m:item name='产品列表' ischannel='1' link='content_list.php?channelid=21' linkadd='archives_add.php?channelid=21' channelid='21' rank='' target='main' />
  <m:item name='幻灯片' ischannel='1' link='content_list.php?channelid=22' linkadd='archives_add.php?channelid=22' channelid='22' rank='' target='main' />
  <m:item name='产品热区' ischannel='1' link='content_list.php?channelid=23' linkadd='archives_add.php?channelid=23' channelid='23' rank='' target='main' />
  <m:item name='产品类别' ischannel='1' link='content_list.php?channelid=24' linkadd='archives_add.php?channelid=24' channelid='24' rank='' target='main' />

  <m:item name='专题管理' ischannel='1' link='content_s_list.php' linkadd='spec_add.php' channelid='-1' rank='spec_New' target='main' />
