
<field:lb1 itemname="类别名称-1" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:lb1>

<field:lb1lj itemname="类别名称-1-链接" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:lb1lj>

<field:lb2 itemname="类别名称-2" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:lb2>
