<li>

							<a href="http://www.babysing.com"><img src="[field:gq1/]" alt="[field:gj1/]"></a>

							<p class="text-center">[field:gj1/]</p>

						</li>

						<li>

								<a href="javascript:;"><img src="[field:gq2/]" alt="[field:gj2/]"></a>

							<p class="text-center">[field:gj2/]</p>

						</li>

						<li>

							<a href="http://www.babysing.com">	<img src="[field:gq3/]" alt="[field:gj3/]"></a>

							<p class="text-center">[field:gj3/]</p>

						</li>

						<li>
		                	<a href="javascript:;"><img src="[field:gq4/]" alt="[field:gj4/]"></a>

							<p class="text-center">[field:gj4/]</p>

						</li>

						<li>

			<a href="javascript:;"><img src="[field:gq5/]" alt="[field:gj5/]"></a>

							<p class="text-center">[field:gj5/]</p>

						</li>

						<li>
                          
								<a href="javascript:;"><img src="[field:gq6/]" alt="[field:gj6/]"></a>

							<p class="text-center">[field:gj6/]</p>

						</li>

						<li>

								<a href="javascript:;"><img src="[field:gq7/]" alt="[field:gj7/]"></a>

							<p class="text-center">[field:gj7/]</p>

						</li>

						<li>

									<a href="javascript:;"><img src="[field:gq8/]" alt="[field:gj8/]"></a>

							<p class="text-center">[field:gj8/]</p>

						</li>

						<li>

								<a href="javascript:;"><img src="[field:gq9/]" alt="[field:gj9/]"></a>

							<p class="text-center">[field:gj9/]</p>

						</li>

						<li>

							<a href="javascript:;"><img src="[field:gq10/]" alt="[field:gj10/]"></a>

							<p class="text-center">[field:gj10/]</p>

						</li>