<?php
$z[0]=Array("pubdate","",262,308);
$z[0][4]=array();
$z[0][4]['function']="strftime(\"%Y\",@me)";
$z[1]=Array("pubdate","",314,360);
$z[1][4]=array();
$z[1][4]['function']="strftime(\"%b\",@me)";
$z[2]=Array("title","",399,413);
$z[2][4]=array();
$z[3]=Array("body","",444,498);
$z[3][4]=array();
$z[3][4]['function']="cn_substr(html2text(@me),600)";
$z[4]=Array("litpic","",610,625);
$z[4][4]=array();
$z[5]=Array("title","",632,646);
$z[5][4]=array();

?>