<?php
$z[0]=Array("pubdate","",257,303);
$z[0][4]=array();
$z[0][4]['function']="strftime(\"%Y\",@me)";
$z[1]=Array("title","",350,433);
$z[1][4]=array();
$z[1][4]['function']="(strlen(\"@me\")>400 ? cn_substr(\"@me\",400).\"...\" : \"@me\")";
$z[2]=Array("description","",464,485);
$z[2][4]=array();
$z[3]=Array("litpic","",600,615);
$z[3][4]=array();
$z[4]=Array("title","",622,636);
$z[4][4]=array();

?>