<li>
						<div class="cen-qr">在线商城</div>
						<img src="[field:zx/]" alt="">
					</li>
					<li>
						<div class="cen-qr"><img src="/templets/default/image/we-logo-qr.png" alt=""></div>
						<img src="[field:wx1/]" alt="">
					</li>

					<li>
						<div class="cen-qr"><img src="/templets/default/image/mo-logo-qr.png" alt=""></div>
						<img src="[field:by/]" alt="">
					</li>
					<li>
						<div class="cen-qr"><img src="/templets/default/image/wei-logo-qr.png" alt=""></div>
						<img src="[field:wb/]" alt="">
					</li>