<?php
$z[0]=Array("include","",2381,2416);
$z[0][4]=array();
$z[0][4]['filename']="head.htm";
$z[1]=Array("arclist","\r\n			<img src=\"[field:ditu/]\" class=\"img-responsive center-block\" alt=\"\">\r\n           ",2674,2851);
$z[1][4]=array();
$z[1][4]['addfields']="ditu";
$z[1][4]['channelid']="27";
$z[1][4]['idlist']="98";
$z[1][4]['orderby']="pubdate";
$z[2]=Array("arclist","\r\n			<h2 class=\"contact-bold\">[field:yw2/]</h2>\r\n			<h3 class=\"contact-zh\">[field:zw2/]</h3>\r\n          ",7693,7949);
$z[2][4]=array();
$z[2][4]['addfields']="yw1,zw1,yw2,zw2,fwrx,tl,qd,tl1,zs,tl2,yx,yx1,zx,wx1,by,wb,yw3,zw3";
$z[2][4]['channelid']="27";
$z[2][4]['idlist']="98";
$z[2][4]['orderby']="pubdate";
$z[3]=Array("arclist","\r\n					<div class=\"col-sm-6\">[field:fwrx/]: [field:tl/]</div>\r\n					<div class=\"col-sm-6\">[field:qd/]: [field:tl1/]</div>\r\n					<div class=\"col-sm-6\">[field:zs/]: [field:tl2/]</div>\r\n					<div class=\"col-sm-6\">[field:yx/]: [field:yx1/]</div>\r\n                          ",8036,8457);
$z[3][4]=array();
$z[3][4]['addfields']="yw1,zw1,yw2,zw2,fwrx,tl,qd,tl1,zs,tl2,yx,yx1,zx,wx1,by,wb,yw3,zw3";
$z[3][4]['channelid']="27";
$z[3][4]['idlist']="98";
$z[3][4]['orderby']="pubdate";
$z[4]=Array("arclist","\r\n					<li>\r\n						<div class=\"cen-qr\">在线商城</div>\r\n						<img src=\"[field:zx/]\" alt=\"\">\r\n					</li>\r\n					<li>\r\n						<div class=\"cen-qr\"><img src=\"/templets/default/image/we-logo-qr.png\" alt=\"\"></div>\r\n						<img src=\"[field:wx1/]\" alt=\"\">\r\n					</li>\r\n\r\n					<li>\r\n						<div class=\"cen-qr\"><img src=\"/templets/default/image/mo-logo-qr.png\" alt=\"\"></div>\r\n						<img src=\"[field:by/]\" alt=\"\">\r\n					</li>\r\n					<li>\r\n						<div class=\"cen-qr\"><img src=\"/templets/default/image/wei-logo-qr.png\" alt=\"\"></div>\r\n						<img src=\"[field:wb/]\" alt=\"\">\r\n					</li>\r\n                     ",8561,9303);
$z[4][4]=array();
$z[4][4]['addfields']="yw1,zw1,yw2,zw2,fwrx,tl,qd,tl1,zs,tl2,yx,yx1,zx,wx1,by,wb,yw3,zw3";
$z[4][4]['channelid']="27";
$z[4][4]['idlist']="98";
$z[4][4]['orderby']="pubdate";
$z[5]=Array("arclist","\r\n				<h2 class=\"contact-bold\">[field:yw3/]</h2>\r\n				<!-- <h3 class=\"contact-zh\">[field:zw3/]</h3> -->\r\n                    ",9494,9771);
$z[5][4]=array();
$z[5][4]['addfields']="yw1,zw1,yw2,zw2,fwrx,tl,qd,tl1,zs,tl2,yx,yx1,zx,wx1,by,wb,yw3,zw3";
$z[5][4]['channelid']="27";
$z[5][4]['idlist']="98";
$z[5][4]['orderby']="pubdate";
$z[6]=Array("include","",11026,11063);
$z[6][4]=array();
$z[6][4]['filename']="footer.htm";

?>