
<field:mingzi itemname="名字" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:mingzi>

<field:youxiang itemname="手机号" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:youxiang>


<field:zhuti itemname="主题" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:zhuti>

<field:liuyan itemname="留言" autofield="1" type="multitext" isnull="true" default=""  maxlength="250" page="">
</field:liuyan>
