<div class="container">
		<div class="text-center">
			<h2 class="contact-bold">[field:yw1/]</h2>
			<h3 class="contact-zh">[field:zw1/]</h3>
		</div>
         <div class="province-shop">
			<h3>上海市</h3>
			<h4>
				<span>普陀旗舰店</span><img src="/templets/default/image/shop-qr.png" style="" alt="">  
				<span>新荟城店</span><img src="/templets/default/image/shop-qr.png" style="" alt="">  
			</h4>
		</div>
		<div class="province-shop">
			<h3>北京市</h3>
			<h4>
				<span>鼓楼大街店</span><img src="/templets/default/image/shop-qr.png" style="" alt="">  
			</h4>
		</div>
		<div class="province-shop">
			<h3>广东省</h3>
			<h4>
				<span>汇一城店</span><img src="/templets/default/image/shop-qr.png" style="" alt="">  
				<span>枫叶路店</span><img src="/templets/default/image/shop-qr.png" style="" alt="">  
			</h4>
		</div>
      
       <div class="province-shop">
			<h3>江苏省</h3>
			<h4>
				<span style="color:black">泰州市</span>:<span>坡子街店</span><img src="/templets/default/image/shop-qr.png" style="" alt="">   
			</h4>
		</div>
      
      <div class="province-shop">
			<h3>浙江省</h3><br/>
			<h4>
              <span style="color:black">杭州市</span>:
				<span>义蓬购物中心店</span><img src="/templets/default/image/shop-qr.png" style="" alt="">   
		
				<span> 邱山大街店</span><img src="/templets/default/image/shop-qr.png" style="" alt="">   
		
				<span>银泰百货店</span><img src="/templets/default/image/shop-qr.png" style="" alt="">   
			</h4><br/>
        
			<h4>
              <span style="color:black">宁波市</span>:
				<span>新江厦店</span><img src="/templets/default/image/shop-qr.png" style="" alt="">   
			</h4><br/>
			<h4>
               <span style="color:black">温州市</span>:
				<span>锦春大厦店</span><img src="/templets/default/image/shop-qr.png" style="" alt="">   
              <span>星海广场店</span><img src="/templets/default/image/shop-qr.png" style="" alt="">   
              <span>瑞安安阳店</span><img src="/templets/default/image/shop-qr.png" style="" alt="">   
			</h4>
		</div>

	</div>