<div class="container">
		<div class="text-center">
			<h2 class="contact-bold">[field:yw1/]</h2>
			<h3 class="contact-zh">[field:zw1/]</h3>
		</div>
         <div class="province-shop">
			<h3>上海市</h3>
			<h4>
				<span>普陀旗舰店</span><img src="/templets/default/image/shop-qr.png" style="" alt="">  
				<span>新荟城店</span><img src="/templets/default/image/shop-qr.png" style="" alt="">  
			</h4>
		</div>
		<div class="province-shop">
			<h3>北京市</h3>
			<h4>
				<span>鼓楼大街店</span><img src="/templets/default/image/shop-qr.png" style="" alt="">  
			</h4>
		</div>
		<div class="province-shop">
			<h3>广东省</h3>
			<h4>
				<span>汇一城店</span><img src="/templets/default/image/shop-qr.png" style="" alt="">  
				<span>枫叶路店</span><img src="/templets/default/image/shop-qr.png" style="" alt="">  
			</h4>
		</div>
      
       <div class="province-shop">
			<h3>江苏省</h3>
			<h4>
				<p style="color:black;display:inline">泰州市</p>:<span>坡子街店</span><img src="/templets/default/image/shop-qr.png" style="" alt="">   
			</h4>
		</div>
      
      <div class="province-shop">
			<h3>浙江省</h3>
			<h4>
              <p style="color:black;display:inline">杭州市</p>:
				<span>义蓬购物中心店</span><img src="/templets/default/image/shop-qr.png" style="" alt="">   
		
				<span> 邱山大街店</span><img src="/templets/default/image/shop-qr.png" style="" alt="">   
		
				<span>银泰百货店</span><img src="/templets/default/image/shop-qr.png" style="" alt="">   
			</h4>
        
			<h4>
              <p style="color:black;display:inline">宁波市</p>:
				<span>新江厦店</span><img src="/templets/default/image/shop-qr.png" style="" alt="">   
			</h4>
			<h4>
               <p style="color:black;display:inline">温州市</p>:
				<span>锦春大厦店</span><img src="/templets/default/image/shop-qr.png" style="" alt="">   
              <span>星海广场店</span><img src="/templets/default/image/shop-qr.png" style="" alt="">   
              <span>瑞安安阳店</span><img src="/templets/default/image/shop-qr.png" style="" alt="">   
			</h4>
		</div>
      
       <div class="province-shop">
			<h3>广西省</h3>
			<h4>
				<p style="color:black;display:inline">柳州市</p>:<span>白沙路店</span><img src="/templets/default/image/shop-qr.png" style="" alt="">   
			</h4>
		</div>
      
       <div class="province-shop">
			<h3>辽宁省</h3>
          <h4>
				<p style="color:black;display:inline">沈阳市</p>:
                  <span>汇宝国际店</span><img src="/templets/default/image/shop-qr.png" style="" alt="">   
			</h4>
			<h4>
				<p style="color:black;display:inline">丹东市</p>:
                  <span>万达金街店</span><img src="/templets/default/image/shop-qr.png" style="" alt="">   
			</h4>
        
		</div>
      
         <div class="province-shop">
			<h3>山东省</h3>
          <h4>
				<p style="color:black;display:inline">临沂市</p>:
                  <span>华山路店</span><img src="/templets/default/image/shop-qr.png" style="" alt="">   
			</h4>
			<h4>
				<p style="color:black;display:inline">威海市</p>:
                  <span>圣迪广场店</span><img src="/templets/default/image/shop-qr.png" style="" alt="">   
			</h4>
           <h4>
				<p style="color:black;display:inline">潍坊市</p>:
                  <span>龙都花园店</span><img src="/templets/default/image/shop-qr.png" style="" alt="">   
			</h4>
           
            <h4>
				<p style="color:black;display:inline">烟台市</p>:
                  <span>老华联店</span><img src="/templets/default/image/shop-qr.png" style="" alt="">   
			</h4>
        
		</div>
        <div class="province-shop">
			<h3>陕西省</h3>
          <h4>
				<p style="color:black;display:inline">西安市</p>:
                  <span>三桥新街店</span><img src="/templets/default/image/shop-qr.png" style="" alt="">   
			</h4>

		</div>
        <div class="province-shop">
			<h3>四川省</h3>
          <h4>
				<p style="color:black;display:inline">成都市</p>:
                  <span>凯德广场店</span><img src="/templets/default/image/shop-qr.png" style="" alt="">   
			</h4>

		</div>

	</div>