<?php
$z[0]=Array("pubdate","",162,215);
$z[0][4]=array();
$z[0][4]['function']="strftime(\"%b %d/ %Y\",@me)";
$z[1]=Array("arcurl","",541,556);
$z[1][4]=array();
$z[2]=Array("title","",574,588);
$z[2][4]=array();
$z[3]=Array("description","",662,682);
$z[3][4]=array();
$z[4]=Array("arcurl","",736,751);
$z[4][4]=array();
$z[5]=Array("arcurl","",1125,1140);
$z[5][4]=array();
$z[6]=Array("litpic","",1168,1183);
$z[6][4]=array();
$z[7]=Array("title","",1210,1224);
$z[7][4]=array();

?>