<?php
$z[0]=Array("pubdate","",162,215);
$z[0][4]=array();
$z[0][4]['function']="strftime(\"%b %d/ %Y\",@me)";
$z[1]=Array("arcurl","",541,556);
$z[1][4]=array();
$z[2]=Array("title","",574,588);
$z[2][4]=array();
$z[3]=Array("description","",661,681);
$z[3][4]=array();
$z[4]=Array("arcurl","",735,750);
$z[4][4]=array();
$z[5]=Array("arcurl","",1124,1139);
$z[5][4]=array();
$z[6]=Array("litpic","",1167,1182);
$z[6][4]=array();
$z[7]=Array("title","",1209,1223);
$z[7][4]=array();

?>