
    <m:item name='新闻资讯' ischannel='1' link='content_list.php?channelid=1' linkadd='article_add.php?channelid=1' channelid='1' rank='' target='main' />
  <m:item name='产品添加' ischannel='1' link='content_i_list.php?channelid=2' linkadd='album_add.php?channelid=2' channelid='2' rank='' target='main' />
  <m:item name='品牌故事大事件' ischannel='1' link='content_ppgs.php?channelid=18' linkadd='ppgs_add.php?channelid=18' channelid='18' rank='' target='main' />
  <m:item name='产品列表' ischannel='1' link='content_list.php?channelid=21' linkadd='archives_add.php?channelid=21' channelid='21' rank='' target='main' />

  <m:item name='专题管理' ischannel='1' link='content_s_list.php' linkadd='spec_add.php' channelid='-1' rank='spec_New' target='main' />
