<?php
$z[0]=Array("pubdate","",166,219);
$z[0][4]=array();
$z[0][4]['function']="strftime(\"%b %d/ %Y\",@me)";
$z[1]=Array("arcurl","",635,650);
$z[1][4]=array();
$z[2]=Array("title","",668,682);
$z[2][4]=array();
$z[3]=Array("description","",757,777);
$z[3][4]=array();
$z[4]=Array("arcurl","",833,848);
$z[4][4]=array();
$z[5]=Array("arcurl","",1228,1243);
$z[5][4]=array();
$z[6]=Array("litpic","",1271,1311);
$z[6][4]=array();
$z[6][4]['function']="firstimg('@me')";
$z[7]=Array("title","",1339,1353);
$z[7][4]=array();

?>