<div class="container">
		<div class="text-center">
			<h2 class="contact-bold">[field:yw1/]</h2>
			<h3 class="contact-zh">[field:zw1/]</h3>
		</div>

		<div class="province-shop">
			<h3>北京市</h3>
			<h4>
				<span>鼓楼大街店</span><img src="/templets/default/image/shop-qr.png" style="" alt="">  
			</h4>
		</div>
		<div class="province-shop">
			<h3>广东省</h3>
			<h4>
				<span>汇一城店</span><img src="/templets/default/image/shop-qr.png" style="" alt="">  
				<span>枫叶路店</span><img src="/templets/default/image/shop-qr.png" style="" alt="">  
			</h4>
		</div>

	</div>