<div class="col-xs-6 col-sm-4">
                    <div class="ls-con text-center">
                        <a href="[field:arcurl/]" title="[field:fulltitle /]" target="_blank"><img src="[field:litpic/]" alt="[field:title/]" class="img-responsive center-block"></a>
                     <a href="[field:arcurl/]" target="_blank"><h4>[field:fulltitle/]</h4></a>
                    </div>
                </div>