<?php
$z[0]=Array("pubdate","",134,187);
$z[0][4]=array();
$z[0][4]['function']="strftime(\"%b %d, %Y\",@me)";
$z[1]=Array("arcurl","",513,528);
$z[1][4]=array();
$z[2]=Array("title","",546,560);
$z[2][4]=array();
$z[3]=Array("description","",634,654);
$z[3][4]=array();
$z[4]=Array("arcurl","",1033,1048);
$z[4][4]=array();
$z[5]=Array("litpic","",1076,1091);
$z[5][4]=array();
$z[6]=Array("title","",1118,1132);
$z[6][4]=array();

?>