<?php
$z[0]=Array("type","\r\n				    <li><a href=\"[field:typelink/]\">New products</a></li>\r\n				    ",617,725);
$z[0][4]=array();
$z[0][4]['typeid']="8";
$z[1]=Array("type","\r\n				    <li><a href=\"[field:typelink/]\">Baby sweater</a></li>\r\n				    ",735,843);
$z[1][4]=array();
$z[1][4]['typeid']="4";
$z[2]=Array("type","\r\n				    <li><a href=\"[field:typelink/]\">Baby protective clothing</a></li>\r\n				    ",853,973);
$z[2][4]=array();
$z[2][4]['typeid']="5";
$z[3]=Array("type","\r\n				    <li><a href=\"[field:typelink/]\">Baby underwear</a></li>\r\n				    ",983,1093);
$z[3][4]=array();
$z[3][4]['typeid']="6";
$z[4]=Array("type","\r\n						<div class=\"col-xs-4\"><a href=\"[field:typelink/]\">New products</a></div>\r\n						",2588,2711);
$z[4][4]=array();
$z[4][4]['typeid']="8";
$z[5]=Array("type","\r\n						<div class=\"col-xs-4\"><a href=\"[field:typelink/]\">Baby sweater</a></div>\r\n						",2719,2842);
$z[5][4]=array();
$z[5][4]['typeid']="4";
$z[6]=Array("type","\r\n						<div class=\"col-xs-4\"><a href=\"[field:typelink/]\">Baby protective clothing</a></div>\r\n						",2850,2985);
$z[6][4]=array();
$z[6][4]['typeid']="5";
$z[7]=Array("type","\r\n						<div class=\"col-xs-4\"><a href=\"[field:typelink/]\">Baby underwear</a></div>\r\n						",2993,3118);
$z[7][4]=array();
$z[7][4]['typeid']="6";

?>